### ISSUE TITLE
Add support to use AlphaFold3 command line outputs in addition to AlphaFold3 Server outputs

### ISSUE THREAD

**Issue by phupe** [PDB-REDO/AlphaBridge#4]
AlphaBridge is really great, thanks for making this tool available.

Is there any plan to add support to use AlphaFold3 command line outputs in addition to AlphaFold3 Server outputs as filenames and json entries are not extacly the same.

Thanks.

**Comment by drlemmus** [comment]
Yes, this is in the works, but I cannot give you an ETA.

**Comment by phupe** [comment]
This is a great news thats this functionnality is on its way.

**Comment by phupe** [comment]
Hi, any news on this implementation? Thanks a lot.

**Comment by ruslan-uoc** [comment]
Hi! I made a fork of the original AlphaBridge repository with enabled support for local installation of AlphaFold3 output. It's a very "crutch"-like solution that simply masks AF3 output as the output of AlphaFold Server and currently doesn't have support for ligands, but it works for proteins. 

https://github.com/ruslan-uoc/AlphaBridge-AF3LocalPatch.git

AlphaBridge is great and I am looking forward for the implementation of this functionality from the authors of the original paper, but until then, I hope it will be of some help. 

Cheers!

**Comment by Dan-salv** [comment]
Sorry for the delay in my response! Thank you for your feedback and for sharing your fork with the community,it’s great to see such engagement. I’m currently working on addressing this issue, alongside adding support for ligands and post-translational modifications. You can expect an update with these improvements by the end of this month.

**Comment by phupe** [comment]
Thanks @ruslan-uoc and @Dan-salv for this information!

**Comment by Dan-salv** [comment]
> Thanks [@ruslan-uoc](https://github.com/ruslan-uoc) and [@Dan-salv](https://github.com/Dan-salv) for this information!

Hi @phupe , I think i replied to you already by mail, but the 'Trunk branch' provides support for the locally installed version output, so I am close the issue

**Comment by MaximePolicarpo** [comment]
Dear Daniel,

I think  I found a minor problem that might be wort indicating somewhere in the help or in the README of the github. It seems like the different sequences/proteins need to be named "A", "B", "C" etc ... following alphabetical order. For example, when running a prediction of a protein with a ligand, if I assign the ligand ID to "S" (in the initial JSON used as input for alphafold3), AlphaBridge returns this error:

```
Traceback (most recent call last):
  File "/shared/ifbstor1/projects/olfactory_receptor/SI_analysis/../AlphaBridge/define_interfaces.py", line 185, in <module>
    main()
  File "/shared/ifbstor1/projects/olfactory_receptor/SI_analysis/../AlphaBridge/define_interfaces.py", line 178, in main
    define_interfaces(in_dir,outdir,mode,sample,plotting)
  File "/shared/ifbstor1/projects/olfactory_receptor/SI_analysis/../AlphaBridge/define_interfaces.py", line 91, in define_interfaces
    chain_info_dict, sequence_info_dict = FEATURE_OBJECT.extract_chain_info_dict()
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/projects/olfactory_receptor/AlphaBridge/src/module/confidence_contact_matrix.py", line 459, in extract_chain_info_dict
    rec_list, sequence_info_dict = self.extract_sequence_info()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/projects/olfactory_receptor/AlphaBridge/src/module/confidence_contact_matrix.py", line 266, in extract_sequence_info
    rec_list = self.extract_rec_list(job_request_path, structure_sequence_list, feature_dict)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/projects/olfactory_receptor/AlphaBridge/src/module/confidence_contact_matrix.py", line 235, in extract_rec_list
    rec_list = RECORD_AF3(request_file, structure_sequence_list, feature_dict).process_record_file()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/projects/olfactory_receptor/AlphaBridge/src/module/rec_input.py", line 101, in process_record_file
    rec_list = self.map_asym_id(rec_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/projects/olfactory_receptor/AlphaBridge/src/module/rec_input.py", line 25, in map_asym_id
    structure_sequence_list_ordered = sorted(structure_sequence_list, key=lambda x: token_chain_ids.index(x[0]))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/ifbstor1/projects/olfactory_receptor/AlphaBridge/src/module/rec_input.py", line 25, in <lambda>
    structure_sequence_list_ordered = sorted(structure_sequence_list, key=lambda x: token_chain_ids.index(x[0]))
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'S' is not in list
```

However, if I assign the ID of the ligand to "B", then everything works perfectly fine. The exact same issue happened if I assigned two proteins ID to "A", "B" and a ligand to "S", but again, got resolved by assigning the ligand to "C". Sorry in advance if this is not a bug but something made in prupose !

Cheers,

Maxime

**Comment by Dan-salv** [comment]
You're correct. This isn't technically a bug, but rather a known behavior in how AlphaFold3 assigns chain IDs. The issue occurs because:  AlphaFold3 automatically generates chain IDs in the output .cif file, which may not match the chain IDs specified in your input JSON if you modify them. As I need to match this two chain IDs, the issue arises. Thanks for raising this it’s a helpful reminder to make the workflow clearer for users. Let me know if you run into any other issues.
